# Generated by Django 3.2.7 on 2021-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0009_auto_20211122_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams',
            name='address',
        ),
        migrations.RemoveField(
            model_name='exams',
            name='admin',
        ),
        migrations.AddField(
            model_name='exams',
            name='exam_name',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='target_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exams',
            name='total_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exams',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
