# Generated by Django 3.2.7 on 2021-11-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0011_auto_20211122_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD')], default=1, max_length=10),
        ),
    ]
