# Generated by Django 3.2.7 on 2021-11-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0012_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
