# Generated by Django 3.2.7 on 2021-11-23 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0013_alter_exams_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics_tracker_app.exams'),
        ),
    ]
