# Generated by Django 3.2.7 on 2021-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0014_alter_subjects_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
