# Generated by Django 3.2.7 on 2021-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0015_subjects_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='marks',
        ),
        migrations.AddField(
            model_name='subjects',
            name='marks_scored',
            field=models.FloatField(default=0),
        ),
    ]
