# Generated by Django 3.2.7 on 2021-12-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics_tracker_app', '0018_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
